---
name: mvn
on:
  push:
    branches:
      - master
    paths-ignore: [ 'paper/**', 'diagrams/**' ]
  pull_request:
    branches:
      - master
    paths-ignore: [ 'paper/**', 'diagrams/**' ]
concurrency:
  group: mvn-${{ github.ref }}
  cancel-in-progress: true
jobs:
  mvn:
    name: mvn
    strategy:
      matrix:
        os: [ ubuntu-20.04 ]
        java: [ 17 ]
    runs-on: ${{ matrix.os }}
    env:
      CONVERT_PATH: /tmp/antlr4-to-bnf-converter
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-jdk-${{ matrix.java }}-maven-
      - run: mvn clean install -Pjacoco --errors --batch-mode
